# site.yml
# ---

- hosts: minecraft
  vars:
  remote_user: ec2-user
  become: yes

  tasks:
  - name: set timezone to Asia/Tokyo
    timezone:
      name: Asia/Tokyo

  - name: Add Group (for systemd)
    group:
      name: appmgr
      state: present

  - name: Add the user 'minecraft'
    user:
      name: minecraft
      group: appmgr

  - name: Create minecraft directory if it does not exist
    file:
      path: /home/minecraft/minecraft
      state: directory
      mode: '0755'
      recurse: yes
      owner: minecraft
      group: appmgr

  - name: set of boot file
    template:
      src: sources/minecraft_boot
      dest: /home/minecraft/minecraft/boot
      owner: minecraft
      group: appmgr
      mode: '0755'

  - name: set of environments file
    template:
      src: sources/environments
      dest: /home/minecraft/minecraft/environments
      owner: minecraft
      group: appmgr
      mode: '0644'

  - name: set of minecraft service file
    template:
      src: sources/systemd_minecraft.service
      dest: /etc/systemd/system/minecraft_server.service

  - name: systemd to set minecraft server
    systemd:
      name: minecraft_server.service
      state: restarted
      daemon_reload: yes
      enabled: true
    become: yes

  # - name: Systemd setting
  #   template:
  #     src:
  #     src: sources/
  #     dest: /etc/file.conf
  #     owner: bin
  #     group: wheel
  #     mode: '0644'

  # - name: Install ntp

  #   yum: name=ntp state=present
  #   tags: ntp

  # - name: Configure ntp file
  #   template: src=ntp.conf.j2 dest=/etc/ntp.conf
  #   tags: ntp
  #   notify: restart ntp

  # - name: Start the ntp service
  #   service: name=ntpd state=started enabled=yes
  #   tags: ntp

  # - name: test to see if selinux is running
  #   command: getenforce
  #   register: sestatus
  #   changed_when: false

# - hosts: database
#   vars:
#     mysql_port: 3306
#     dbname: somedb
#     dbuser: someuser
#     dbpass: somepass
#   remote_user: user
#   become: yes

#   tasks:
#   - name: Install Mysql package
#     yum: name={{ item }} state=installed
#     with_items:
#      - mysql-server
#      - MySQL-python
#      - libselinux-python
#      - libsemanage-python

#   - name: Configure SELinux to start mysql on any port
#     seboolean: name=mysql_connect_any state=true persistent=yes
#     when: sestatus.rc != 0

#   - name: Create Mysql configuration file
#     template: src=my.cnf.j2 dest=/etc/my.cnf
#     notify:
#     - restart mysql

#   - name: Start Mysql Service
#     service: name=mysqld state=started enabled=yes

#   - name: insert iptables rule
#     lineinfile: dest=/etc/sysconfig/iptables state=present regexp="{{ mysql_port }}" insertafter="^:OUTPUT " line="-A INPUT -p tcp --dport {{ mysql_port }} -j ACCEPT"
#     notify: restart iptables

#   - name: Create Application Database
#     mysql_db: name={{ dbname }} state=present
